### ISSUE TITLE
[Feature] Support ScaNN index

### ISSUE THREAD

**Issue by chasingegg** [milvus-io/knowhere#1018]
As many users want to have scann index feature in the milvus community, we decide to support it.

**Comment by xiaofan-luan** [comment]
Any performance benchmark and document for ScaNN index yet?

**Comment by chasingegg** [comment]
here it is, I guess you have seen it https://zilliverse.feishu.cn/docx/Z1dzdrRGPoUCycxiQXUc7sTznec, document teams are working on it for milvus website.

**Comment by xiaofan-luan** [comment]
please have a english version if possible, thanks
