### ISSUE TITLE
Need to fix warning problems of compilation

### ISSUE THREAD

**Issue by landyliu** [milvus-io/knowhere#219]
Recently,  I found lots of warning message poped up when compiled on my Mac.  
These warning messages are mainly of the following two types:
1. type mismatch
> `In file included from /Users/zilliz/knowhere/unittest/test_ivf_nm.cpp:35:
> warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat] 
> (accuracy_cnt * 1.0f / size), accuracy_cnt, size);`

2. unused lib link during compilation
> ` 7 warnings generated.
> clang-13: warning: argument unused during compilation: '-L/usr/local/opt/libomp/lib' [-Wunused-command-line-argument]
> /Users/zilliz/knowhere/unittest/benchmark/benchmark_knowhere_binary_range.cpp:45:50: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat]
>                std::string(index_type_).c_str(), nlist);
>                                                  ^~~~~
> 1 warning generated.`

**Comment by xiaofan-luan** [comment]
> Recently, I found lots of warning message poped up when compiled on my Mac. These warning messages are mainly of the following two types:
> 
> 1. type mismatch
> 
> > `In file included from /Users/zilliz/knowhere/unittest/test_ivf_nm.cpp:35: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]  (accuracy_cnt * 1.0f / size), accuracy_cnt, size);`
> 
> 2. unused lib link during compilation
> 
> > ` 7 warnings generated. clang-13: warning: argument unused during compilation: '-L/usr/local/opt/libomp/lib' [-Wunused-command-line-argument] /Users/zilliz/knowhere/unittest/benchmark/benchmark_knowhere_binary_range.cpp:45:50: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat] std::string(index_type_).c_str(), nlist); ^~~~~ 1 warning generated.`

good catch, I also find some warning on MAC

**Comment by cydrain** [comment]
> 
> 1. type mismatch
> 
> > `In file included from /Users/zilliz/knowhere/unittest/test_ivf_nm.cpp:35: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]  (accuracy_cnt * 1.0f / size), accuracy_cnt, size);`
> 
when change "%ld" to "%lld", ubuntu start to report building warnings:
![Screenshot from 2022-06-22 15-32-32](https://user-images.githubusercontent.com/3992404/174971344-2064d691-2e25-4237-ae80-a5f9953c48e4.png)

**Comment by cydrain** [comment]
> 
> 2. unused lib link during compilation
> 
> > ` 7 warnings generated. clang-13: warning: argument unused during compilation: '-L/usr/local/opt/libomp/lib' [-Wunused-command-line-argument] /Users/zilliz/knowhere/unittest/benchmark/benchmark_knowhere_binary_range.cpp:45:50: warning: format specifies type 'long' but the argument has type 'long long' [-Wformat] std::string(index_type_).c_str(), nlist); ^~~~~ 1 warning generated.`

When support knowhere build on Mac, I have already taken lots of effort to clean this warning but failed.
Maybe someone else can have a try.

**Comment by hhy3** [comment]
> Mac expects to use "%lld" to print int64_t, while ubuntu expects to use "%ld" to print int64_t. We cannot fit them all. So just let it be.

Maybe you can use 
```c++
#include <cinttypes>
printf("%" PRId64 "\n", (int64_t)42);
``` 
to print 64bit signed integers (but it's a bit ugly)
