### ISSUE TITLE
Distance calculation is not accuate enough

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/knowhere#235]
L2 distance calculated in Knowhere is not the mathematics L2 distance. 
So
 1) whether it will impact the results of range search.
 2) whether it will has gap with users' expectation

**Comment by cydrain** [comment]
L2 distance formula is like this: (||x||^2 - 2*||x||||y|| + ||y||^2) ^ 1/2
In knowhere, in considering of efficiency, it only calculate: ||x||^2 - 2||x||*||y|| + ||y||^2 and sort the result in ascending order.

IP distance formula is like this: (||x||^2 - 2*||x||*||y|| + ||y||^2) ^ 1/2
IP's vector has been normalized, then ||x||^2 == 1 and ||y||^2 == 1.
So in knowhere, it only calculate ||x|| * ||y||, and sort the result in descending order.
