### ISSUE TITLE
Remove openblas support in knowhere

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/knowhere#242]
Upon our test, openblas spend much longer time in computation when nq is large.
Also openblas brings great maintainence and installation trouble in knowhere.

What is the gain of introducing knowhere, any ideas?

**Comment by cydrain** [comment]
@xiaofan-luan 
openblas is used in many places in faiss, it may take a lot of effort to let faiss build pass without openblas

Taks API "sgemm_" as an example, it's used in following faiss files:
faiss/IndexHNSW.cpp
faiss/VectorTransform.cpp
faiss/impl/AdditiveQuantizer.cpp
faiss/impl/LocalSearchQuantizer.cpp
faiss/impl/ProductQuantizer.cpp
faiss/impl/ResidualQuantizer.cpp

**Comment by cydrain** [comment]
@xiaofan-luan 
I can test if SIMD is always faster than openblas for IDMAP search, if so I can remove openblas for IDMAP.

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan openblas is used in many places in faiss, not only in brute force search. It may take a lot of effort to let faiss build pass without openblas.
> 
> Taks API "sgemm_" as an example, it's used in following faiss files: faiss/IndexHNSW.cpp faiss/VectorTransform.cpp faiss/impl/AdditiveQuantizer.cpp faiss/impl/LocalSearchQuantizer.cpp faiss/impl/ProductQuantizer.cpp faiss/impl/ResidualQuantizer.cpp

The easiest way is to change the config to use openblas to a very high threshold, which might work

**Comment by cydrain** [comment]
see #244
