### ISSUE TITLE
Building binary ivf index 3 times slower since v1.1.14

### ISSUE THREAD

**Issue by cydrain** [milvus-io/knowhere#278]
When running knowhere benchmark, we found since knowhere-v1.1.14,
binary ivf index building time change from 102s to 362s

**Comment by cydrain** [comment]
it's caused by https://github.com/milvus-io/knowhere/pull/246

**Comment by cydrain** [comment]
Build IVF_FLAT_NM on sift1M, with nlist = [4, 16, 64, 256, 1024]
        | threshold = 0 | threshold = 65535 | threshold = 16384
-------|-------------------|--------------------------|-------------------------
nprobe = 4 | 0.180s | 0.136s | 0.151s
nprobe = 16 | 0.155s | 0.160s | 0.157s
nprobe = 64 | 0.350s | 0.328s | 0.330s
nprobe = 256 | 1.303s | 1.301s | 1.278s
nprobe = 1024 | 10.755s | 10.432s | 11.010s

**Comment by xiaofan-luan** [comment]
why do we simply change the parameter?
Does this parameter really make sense？
should index build and search use the same parameter?

**Comment by cydrain** [comment]
> why do we simply change the parameter? 
in #242, you suggest to remove openblas support in knowhere, changing this parameter to a big value is the simplest way to disable openblas.

> Does this parameter really make sense？
Yes.

> should index build and search use the same parameter?
build and search all the same API knn_L2sqr(), in this API it use "distance_compute_blas_threshold" to decide to use SIMD or BLAS to compute vector distance.
