### ISSUE TITLE
HNSW keeps searching for 10 mins, memory uagege increased from 2GB to 15GB

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/knowhere#344]
dataset: sift-128d-1m 
ef = 16
radius = 186 * 3
keep searching and range searching for 10 mins
memory increased from 2GB to 15GB, cpu usage is stable when searching

**Comment by yanliang567** [comment]
it runs into OOM after 29mins with memory limit 32GB.

**Comment by cydrain** [comment]
Faiss uses API RangeSearchResult::do_allocation() to alloc memory for range search result, new/delete is used in this API.
Also in HNSW range search, new/delete is used for range search result.
We should use new/delete in Dataset and all Knowhere Query().

**Comment by cydrain** [comment]
Hi @yanliang567, can you retest this issue ?

**Comment by yanliang567** [comment]
/assign @haorenfsa 
please help to verify the fix.
/unassign

**Comment by xiaofan-luan** [comment]
@yanliang567 
why we did get on knowhere test cases?

**Comment by xiaofan-luan** [comment]
@elstic

**Comment by xiaofan-luan** [comment]
I believe this is the very fundamental test we should run against range search

**Comment by elstic** [comment]
> I believe this is the very fundamental test we should run against range search

@xiaofan-luan 

Yes, we have these test cases and I will check if this problem still exists

**Comment by elstic** [comment]
knowhere main branch 
nq = topk = 10;
radius = 558.0
M = 16
EFCONSTRUCTION = 200
dataset: sift 128d
ef = 16

keep searching and range searching for 2 hours
memory increased from 1GB to 29GB, cpu usage is stable when searching

![image](https://github.com/milvus-io/knowhere/assets/48523564/4c687a76-458a-4310-bd8d-7a60eee78ae7)

**Comment by xiaofan-luan** [comment]
/assign @cydrain 
please help on it

**Comment by elstic** [comment]
update: When I remove the log from the case and re-execute the case with the same parameters, it runs for 1h with no memory increase.

before:
![image](https://github.com/milvus-io/knowhere/assets/48523564/c9d1efbe-6f73-4fb7-9a11-0c1dbd8caacc)



after:
![image](https://github.com/milvus-io/knowhere/assets/48523564/4ca15990-85f5-455e-9995-bd540aa5d673)

and now memory usage:
![image](https://github.com/milvus-io/knowhere/assets/48523564/7fb6073c-a0a6-4b36-9054-426ffe41bc44)


Conclusion: It is possible that there is a memory leak in the python log, and the subsequent stability case will remove the log.

**Comment by cydrain** [comment]
ok, please close this issue.
