### ISSUE TITLE
Incorrect search result for Tanimoto

### ISSUE THREAD

**Issue by yhmo** [milvus-io/knowhere#500]
Use this script to test:

```
from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection, utility
# this needs the bitstring package
import bitstring

COLLECTION_NAME = 'tanimoto_test'
VECTOR_DIMENSION = 8
METRIC_TYPE = 'TANIMOTO'
HOST = '127.0.0.1'
PORT = '19530'


V1 = b'\x0b'
V2 = b'\x06'


def load():
    connections.connect(
        alias='default',
        host=HOST,
        port=PORT)

    # don't try to create collection and load data if it has already been done
    if utility.has_collection(COLLECTION_NAME):
        connections.disconnect('default')
        return

    fld_idx = FieldSchema(name="id", dtype=DataType.INT64, descrition="int64 primary id",
                          is_primary=True)
    fld_fingerprint = FieldSchema(name="fingerprint", dtype=DataType.BINARY_VECTOR,
                                  descrition="binary vector fingerprint",
                                  dim=VECTOR_DIMENSION, is_primary=False)

    schema = CollectionSchema(fields=[fld_idx, fld_fingerprint],
                              description="test")
    collection = Collection(name=COLLECTION_NAME, schema=schema, using='default')
    assert len(V1) == VECTOR_DIMENSION // 8
    assert len(V2) == VECTOR_DIMENSION // 8
    r = collection.insert([[1, 2], [V1, V2]])
    print(f'Inserted: {r}')
    connections.disconnect('default')


def test():
    connections.connect(
        alias='default',
        host=HOST,
        port=PORT)
    collection = Collection(name=COLLECTION_NAME)
    collection.load()
    search_params = {"metric_type": METRIC_TYPE}
    res = collection.search([V1], anns_field="fingerprint", param=search_params, limit=2)
    r = res[0]
    print(f'Search result: {r}')

    v1 = {"bin_vectors": [V1]}
    v2 = {"bin_vectors": [V2]}
    
    collection.release()
    collection.drop()
    connections.disconnect('default')

    ba1 = bitstring.BitArray(auto=V1)
    ba2 = bitstring.BitArray(auto=V2)
    print("ba1", ba1.bin)
    print("ba2", ba2.bin)
    ba_and = ba1 & ba2  #  intersection (common bits)
    ba_or = ba1 | ba2   #  union (all bits)

    print(f'1 bit counts: b1: {ba1.count(1)}, b2: {ba2.count(1)}, intersect: {ba_and.count(1)}, union: {ba_or.count(1)}')

    tanimoto_sim1 = ba_and.count(1) / ba_or.count(1)
    # alternatively, we can compute it like this, which should give us identical results
    tanimoto_sim2 = ba_and.count(1) / (ba1.count(1) + ba2.count(1) - ba_and.count(1))
    print(f'True Tanimoto similarity method 1: {tanimoto_sim1}, method 2: {tanimoto_sim2}')


if __name__ == '__main__':
    load()
    test()
    print('Done.')
```

In the search result, the top1 result should be 0.25, but it returns 0.0
```
Search result: ['(distance: 0.0, id: 1)', '(distance: 2.0, id: 2)']
ba1 00001011
ba2 00000110
1 bit counts: b1: 3, b2: 2, intersect: 1, union: 4
True Tanimoto similarity method 1: 0.25, method 2: 0.25
```

**Comment by cydrain** [comment]
![Screenshot from 2022-10-12 17-53-13](https://user-images.githubusercontent.com/3992404/195311730-b7bb4a19-7bdf-4bc1-9282-76c71371ad74.png)

**Comment by cydrain** [comment]
in knowhere, we calculate TANIMOTO distance by transforming JACCARD distance using this formula:
```
/**
 * Distance conversion between Jaccard and Tanimoto
 */
inline float Jaccard_2_Tanimoto(float jcd) {
    // To avoid a negative zero in C language
    return (jcd == 0.0) ? 0.0 : -log2(1 - jcd);
}

inline float Tanimoto_2_Jaccard(float tnmt) {
    return 1 - pow(2.0, -tnmt);
}
```

In this case, 
```
d(Jaccard) = (4 - 1) / 4 = 0.75
d(Tanimoto) = -log2(1 - 0.75) = 2
```

**Comment by drassokhin** [comment]
So, different definitions of 'Tanimoto distance' for binary vectors are used in different places in the API and documentation, which is really, really confusing. ```TanimotoDistanceScore := -log2(JaccardSimilarity)``` vs. ```TanimotoDistance := 1.0 - JaccardSimilarity``` Note that TaminotoDistanceScore is not a true distance metric. In addition to that, utility.calc_distance method implementation had a bug, which resulted in the returned value to be neither TanimotoDistanceScore nor TanimotoDistance when called with ```params = {"metric_type": "TANIMOTO"}```.

**Comment by cydrain** [comment]
The relation between Tanimoto distance and Jaccard distance is:
```
 tanimoto = (jcd == 0.0) ? 0.0 : -log2(1 - jcd);
```
when Jaccard distance is 0.0, Tanimoto distance is also 0.0

**Comment by drassokhin** [comment]
> The relation between Tanimoto distance and Jaccard distance is:
> 
> ```
>  tanimoto = (jcd == 0.0) ? 0.0 : -log2(1 - jcd);
> ```
> 
> when Jaccard distance is 0.0, Tanimoto distance is also 0.0

Yes, I know, but:

1. this is not reflected in the documentation: https://milvus.io/docs/v2.1.x/metric.md says "For binary variables, the Tanimoto coefficient is equivalent to Jaccard distance". In literature, two different definitions of Tanimoto distance can be found, and the documentation must specify which one Milvus uses, the one where, for binary vectors, Tanimoto distance is the same as Jaccard distance, or the one where Tanimoto distance is -log2(JaccardSimilarity).
2. the Tanimoto distances returned by search are different from the ones computed via 'calc_distance', see https://github.com/milvus-io/milvus/discussions/19688
3. computing ```tanimoto = (jcd == 0.0) ? 0.0 : -log2(1 - jcd)``` by first calculating the Jaccard distance and then computing ```-log2(1 - jcd)``` for binary vectors is very computationally inefficient. I have not looked into the code, but I hope this is not how Milvus computes the Tanimoto distances when searching and indexing collections of bit vectors.

Also, in the above comment I asked the question about what happens when the Jaccard distance is 1 (that is, the two bitsets have no set bits in common). When this happens, the result of ```-log2(1.0 - 1.0)``` is ```+Inf```, and my question was about how Milvus would handle this situation.

**Comment by cydrain** [comment]
Hi @yhmo,

I plan to remove the metric TANIMOTO, you can find the reason in this doc:
https://zilliverse.feishu.cn/docx/UmMOdgaJ9oYilLxVWdIcOnvXnwh

Please let me know your opinion.

**Comment by cydrain** [comment]
We'll remove 3 binary metrics: TANIMOTO, SUPERSTRUCTURE, SUBSTRUCTURE,
only support: HAMMING, JACCARD

close this issue
/close
