### ISSUE TITLE
Can I replace this knowhere to the milvus ?

### ISSUE THREAD

**Issue by zhuyaguang** [milvus-io/knowhere#58]
This knowhere code how to  sync milvus repo ?

**Comment by xiaofan-luan** [comment]
this repo is still under dev~~
after milvus 2.0-ga release we are gonna to remove milvus repo knowhere and rely on this implementation

**Comment by jaime0815** [comment]
knowhere as a third party lib provides to Milvus repo, you can see more detail [here]( https://github.com/milvus-io/milvus/blob/knowhere/internal/core/thirdparty/knowhere/CMakeLists.txt)
