### ISSUE TITLE
[bug]: [knowhere2.0] Set nq= topk = 10000, stability test, memory keeps going up, pod crashes

### ISSUE THREAD

**Issue by elstic** [milvus-io/knowhere#619]
knowhere version: main.20221222.7f3df99

### Current Behavior

Execution Script：
```
pytest -v -m L3 test_hnsw.py --timeout   86400
```

When setting nq=topk=10000, memory keeps going up and pod crashes

![image](https://user-images.githubusercontent.com/48523564/210311586-be78f4c5-a69b-4af1-be79-96f7a620aa48.png)

```
pytest -v -m L3 test_bin_ivf.py --timeout    86400
```

![image](https://user-images.githubusercontent.com/48523564/210311614-21b08625-5102-4843-a35b-ec67db92be0b.png)

**Comment by cydrain** [comment]
HNSW, nq = 10000, topk = 10000
memory increases from 0 to 30G after running 25 times search,
each search leaks 1.2G memory

result dataset occupies:
(4 + 8) * 10000 * 10000 = 1.2G

so the memory leak must come from result dataset

**Comment by cydrain** [comment]
HNSW, nq = 10000, topk = 10000
memory increases from 0 to 30G after running 25 times search,
each search leaks 1.2G memory

result dataset occupies:
(4 + 8) * 10000 * 10000 = 1.2G

so the memory leak must come from result dataset

**Comment by cydrain** [comment]
see no memory leak using valgrind
[test_knowhere_hnsw.log](https://github.com/milvus-io/knowhere/files/10352406/test_knowhere_hnsw.log)

**Comment by elstic** [comment]
After a round of verification, it has been fixed .

hnsw index persistent search：
![21777d97-c1b5-404d-97a5-46e53eb2364d](https://user-images.githubusercontent.com/48523564/211447403-a1988e42-2a56-4fd7-b5b0-b0d62d49c8e6.jpeg)

bin_ivf_flat index persistent search :
![1ba273a9-52cc-424b-b895-06e625631941](https://user-images.githubusercontent.com/48523564/211447409-1b019e8a-d851-427d-8399-1209553f50d2.jpeg)

**Comment by elstic** [comment]
A similar question arises ： https://github.com/milvus-io/knowhere/issues/706
