### ISSUE TITLE
[bug]: [knowhere2.0] Set nq= topk = 10, hnsw index continuoussearch for stability testing， memory keeps going up, pod crashes

### ISSUE THREAD

**Issue by elstic** [milvus-io/knowhere#706]
knowhere version:  main.20230221.d067ddc

### Current Behavior
To perform a recurrence, you can perform the following footsteps：
```
pytest -v -m L3 test_hnsw.py::TestHnsw::test_hnsw_search --timeout   86400
```
(86400 is the duration, which can be reduced when reproduced , case from knowhere-test repo, feature-2.0 branch)

When setting nq=topk=10, memory keeps going up and pod crashes：

![image](https://user-images.githubusercontent.com/48523564/221118976-b024b05c-a9cc-4598-aa06-99adae792fdb.png)

pod name: "4am-knowhere-89-wwv9m-gvdc3-tv8rj"
namespace: "jenkins"

**Comment by elstic** [comment]
assign  @Presburger

**Comment by liliu-z** [comment]
Can we still reproduce it? Or we can close it? @elstic

**Comment by elstic** [comment]
> Can we still reproduce it? Or we can close it? @elstic

I'll restart the case today and see if the phenomenon still exists .

**Comment by elstic** [comment]
It has not recently resurfaced
