### ISSUE TITLE
[bug]:[2.0] Diskann index memory leak 

### ISSUE THREAD

**Issue by elstic** [milvus-io/knowhere#762]
Set nq and topk to 10000, diskann index puresearch for stability test, memory leak appears 

knowhere version: main.20230306.636918e

run :
```
pytest -v -m L3 test_diskann.py::TestKNN::test_diskann_search --timeout  18000
```

memory phenomenon：
![image](https://user-images.githubusercontent.com/48523564/226793983-016d2ea5-d62d-4c3c-a576-e70eb7b8ee0a.png)

**Comment by xiaofan-luan** [comment]
seems not a leak, diskANN will cache some active data and seems there is a limitation there

**Comment by xiaofan-luan** [comment]
BTW, @cqy123456 could you make sure that the cache limitation per segment is shared or separate?
If I have two diskANN segments, each of the segments requires certain percentage of cache or it's in total

**Comment by cqy123456** [comment]
A diskann segment has its own cache, the cache occupies 1/8 of the segment size.

**Comment by cqy123456** [comment]
This does not seem to be a memory leak, but rather the search task not run within the specified time by the low local disk I/O that causes.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/39671710/227794167-d855bb1a-53c9-4fad-95ed-39d9d05d4cc9.png">
The I/O throughput of local SATA HDD is about 314，search nq = 10000 and topk = 10000， search list size = 15000 may cost 11h to 15h.
