### ISSUE TITLE
Knowhere didn't maintain the Topk limitation same for every index.

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/knowhere#808]
If user tune the topk limit on milvus, the behaviour of current knowhere 1.x is weird:
1. for faiss, it looks ok and will just accept the top K
2. for HNSW.  ef needs to be larger than topK limit and smaller than HNSW_MAX_EF. since HNSW_MAX_EF is a fixed number, topk is actually fixed to be less than HNSW_MAX_EF but we did't have ensure it.
3. for diskANN, I didn't find anywhere limit topk, is there any where?

**Comment by xiaofan-luan** [comment]
what happens in knowhere 2.0 if topk is larger than ef? 
I don't find any limitation on it

**Comment by cydrain** [comment]
Hi @cqy123456 , can you help to check the topk limitation in Diskann
