### ISSUE TITLE
[bug]:[COSINE] metric_type cosine, GetVectorByIds returns the original vector, not normalized

### ISSUE THREAD

**Issue by elstic** [milvus-io/knowhere#838]
metric_type: COSINE

```
_, result_ids = knowhere.DataSetToArray(ans)
ids = knowhere.ArrayToDataSet(result_ids[2])
result, _ = idx.GetVectorByIds(ids, build_cfg)
raw_vec = knowhere.GetVectorDataSetToArray(result)
degraded += utils.verify_raw_vector(raw_vec, train_vec, result_ids[2])
```

![image](https://user-images.githubusercontent.com/48523564/233978916-b94bc22f-c30f-48a9-afd9-2cb493d47b4a.png)

**Comment by cydrain** [comment]
which index type ? @elstic

**Comment by xiaofan-luan** [comment]
@elstic we are expecting for original index right?

**Comment by cydrain** [comment]
> > which index type ? @elstic
> 
> HNSW 、IVF_FLAT

That's impossible, please make sure if the original dataset is already normalized.

**Comment by cydrain** [comment]
> > which index type ? @elstic
> 
> HNSW 、IVF_FLAT

it's impossible, please check if the original dataset is already normalized.

**Comment by elstic** [comment]
> @elstic we are expecting for original index right?

Currently metric_type  cosine does not support GetVectorByIds, @cydrain support and then return to verify the test here

**Comment by cydrain** [comment]
HNSW + COSINE can support GetVectorByIds now, but IVF_FLAT still not.
please re-test this case.
@elstic

**Comment by elstic** [comment]
> HNSW + COSINE can support GetVectorByIds now, but IVF_FLAT still not. please re-test this case. @elstic

Verified and fixed .
