### ISSUE TITLE
More detailed error information is needed

### ISSUE THREAD

**Issue by jiaoew1991** [milvus-io/knowhere#870]
issue: https://github.com/milvus-io/milvus/issues/24010

When encountering an error in Milvus, only the parameter error is known, but the specific reason for the error is unknown. By checking Knowhere's logs, the specific error information can be found.
 
It is necessary to return the specific error information for error diagnosis.

**Comment by cydrain** [comment]
add more error logs when return error code
https://github.com/milvus-io/knowhere/pull/902
