### ISSUE TITLE
Diskann GetVectorByIds latency not stable

### ISSUE THREAD

**Issue by cydrain** [milvus-io/knowhere#919]
Diskann GetVectorByIds latency not stable, can reproduce with following patch

branch: main
commit: 2fdbe7f4
[diskann_getvector.diff.txt](https://github.com/milvus-io/knowhere/files/11685561/diskann_getvector.diff.txt)

build: make test-cpp
run: cmake_build/bin/all_tests --gtest_filter="*IndexGetVector*"

**Comment by cydrain** [comment]
![Screenshot from 2023-06-08 16-11-48](https://github.com/milvus-io/knowhere/assets/3992404/5d14fc78-d925-4b27-b974-094db78229b3)

**Comment by PwzXxm** [comment]
Decreased around 23% of total time and 50% when concurrency was high. It should now perform much better when concurrency is high or the number of requested IDs is large.

The fluctuations of I/O latency are considered normal to NVMe SSD. See PR #935
